name: 'Terraform'

on:
  pull_request:
    types: [opened, closed]
  push:
    branches: [main]

permissions:
  contents: read

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

jobs:
  terraform-pre-merge:
    name: 'Terraform Pre-Merge'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan (Pre-Merge)
        run: terraform plan -input=false

  terraform-post-merge:
    name: 'Terraform Post-Merge'
    runs-on: ubuntu-latest
    environment: production
    needs: terraform-pre-merge

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan (Post-Merge)
        run: terraform plan -input=false

      - name: Terraform Apply (Post-Merge)
        run: terraform apply -auto-approve -input=false
        if: github.event.pull_request.merged == true
